### ISSUE TITLE
Minimal non-Slurm paired test failed

### ISSUE THREAD

**Issue by alexpreynolds** [meuleman/epilogos#28]
When running the minimal, non-Slurm paired test, I get the following `numpy`-related error: 

```
TypeError: Cannot compare types 'ndarray(dtype=int32)' and 'str'
```

Details:

```
(epilogos_052421_v3) areynolds@Earl-Grey epilogos % tmp_dir=$(mktemp -d -t epilogos-paired-XXXXXXXXXX)
(epilogos_052421_v3) areynolds@Earl-Grey epilogos % epilogos -m paired -l -a data/pyData/male/ -b data/pyData/female/ -n data/state_metadata/human/Boix_et_al_833_sample/hg19/18/metadata.tsv -o ${tmp_dir}


                  d8b 888                                     
                  Y8P 888                                     
                      888                                     
 .d88b.  88888b.  888 888  .d88b.   .d88b.   .d88b.  .d8888b  
d8P  Y8b 888 "88b 888 888 d88""88b d88P"88b d88""88b 88K      
88888888 888  888 888 888 888  888 888  888 888  888 "Y8888b. 
Y8b.     888 d88P 888 888 Y88..88P Y88b 888 Y88..88P      X88 
 "Y8888  88888P"  888 888  "Y88P"   "Y88888  "Y88P"   88888P' 
         888                            888                   
         888                       Y8b d88P                   
         888                        "Y88P"                    


Input Directory 1 = /Users/areynolds/Developer/Github/epilogos/data/pyData/male
Input Directory 2 = /Users/areynolds/Developer/Github/epilogos/data/pyData/female
State Model = 18
Saliency level = 1
Output Directory = /var/folders/h5/sggy_r7s355gnwssgl9mw44c0000gq/T/epilogos-paired-XXXXXXXXXX.v0iSPsWB
Number of Cores = All available
Quiescent State = 18

STEP 1: Per data file background frequency calculation
    epilogos_matrix_chr1		[Done]

STEP 2: Background frequency combination
    [Done]

STEP 3: Score calculation
    epilogos_matrix_chr1	.........	[Done]

STEP 4: Generating p-values and figures
    Fitting distances		[Done]
    Reading in files		[Done]
    Calculating p-vals		[Done]
    Writing metrics		[Done]
    Benjamini-Hochberg procedure		[Done]
    Greatest hits txt	Traceback (most recent call last):
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/bin/epilogos", line 33, in <module>
    sys.exit(load_entry_point('epilogos', 'console_scripts', 'epilogos')())
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/areynolds/Developer/Github/epilogos/epilogos/__main__.py", line 64, in main
    runEpilogos(mode, commandLineBool, inputDirectory, inputDirectory1, inputDirectory2, outputDirectory, stateInfo, saliency,
  File "/Users/areynolds/Developer/Github/epilogos/epilogos/epilogos.py", line 214, in main
    pairwiseVisual.main(inputDirPath.name, inputDirPath2.name, stateInfo, outputDirPath, fileTag, numProcesses,
  File "/Users/areynolds/Developer/Github/epilogos/epilogos/pairwiseVisual.py", line 106, in main
    createTopScoresTxt(roiPath, locationArr, chrDict, distanceArrReal, maxDiffArr, stateNameList, pvals, False, mhPvals)
  File "/Users/areynolds/Developer/Github/epilogos/epilogos/pairwiseVisual.py", line 548, in createTopScoresTxt
    locations = pd.DataFrame(np.concatenate((locationArr[indices], distanceArr[indices].reshape(len(indices), 1),
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/lib/python3.9/site-packages/pandas/core/frame.py", line 4379, in replace
    return super().replace(
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/lib/python3.9/site-packages/pandas/core/generic.py", line 6500, in replace
    return self.replace(
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/lib/python3.9/site-packages/pandas/core/frame.py", line 4379, in replace
    return super().replace(
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/lib/python3.9/site-packages/pandas/core/generic.py", line 6518, in replace
    return self._replace_columnwise(mapping, inplace, regex)
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/lib/python3.9/site-packages/pandas/core/frame.py", line 4415, in _replace_columnwise
    newobj = ser.replace(target, value, regex=regex)
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/lib/python3.9/site-packages/pandas/core/series.py", line 4563, in replace
    return super().replace(
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/lib/python3.9/site-packages/pandas/core/generic.py", line 6543, in replace
    new_data = self._mgr.replace_list(
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 642, in replace_list
    masks = [comp(s, mask, regex) for s in src_list]
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 642, in <listcomp>
    masks = [comp(s, mask, regex) for s in src_list]
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 636, in comp
    return _compare_or_regex_search(values, s, regex, mask)
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 1992, in _compare_or_regex_search
    _check_comparison_types(False, a, b)
  File "/Users/areynolds/miniconda3/envs/epilogos_052421_v3/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 1971, in _check_comparison_types
    raise TypeError(
TypeError: Cannot compare types 'ndarray(dtype=int32)' and 'str'
```

My run environment:

```
(epilogos_052421_v3) areynolds@Earl-Grey epilogos % python --version
Python 3.9.4
(epilogos_052421_v3) areynolds@Earl-Grey epilogos % conda list                                                                               
# packages in environment at /Users/areynolds/miniconda3/envs/epilogos_052421_v3:
#
# Name                    Version                   Build  Channel
ca-certificates           2020.12.5            h033912b_0    conda-forge
certifi                   2020.12.5        py39h6e9494a_1    conda-forge
click                     7.1.2                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.23                  pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
libcxx                    11.1.0               habf9029_0    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
matplotlib                3.3.2                    pypi_0    pypi
natsort                   7.1.1                    pypi_0    pypi
ncls                      0.0.57                   pypi_0    pypi
ncurses                   6.2                  h2e338ed_4    conda-forge
numpy                     1.19.2                   pypi_0    pypi
openssl                   1.1.1k               h0d85af4_0    conda-forge
pandas                    1.1.3                    pypi_0    pypi
patsy                     0.5.1                    pypi_0    pypi
pillow                    8.2.0                    pypi_0    pypi
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7                    pypi_0    pypi
pyranges                  0.0.97                   pypi_0    pypi
pyrle                     0.0.32                   pypi_0    pypi
python                    3.9.4           h9133fd0_0_cpython    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1                   pypi_0    pypi
readline                  8.1                  h05e3726_0    conda-forge
scipy                     1.5.2                    pypi_0    pypi
setuptools                49.6.0           py39h6e9494a_3    conda-forge
six                       1.16.0                   pypi_0    pypi
sorted-nearest            0.0.33                   pypi_0    pypi
sqlite                    3.35.5               h44b9ce1_0    conda-forge
statsmodels               0.12.0                   pypi_0    pypi
tabulate                  0.8.9                    pypi_0    pypi
tk                        8.6.10               h0419947_1    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
```

**Comment by jacobquon** [comment]
Fixed 06/03/2021
